// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrvxqciacyrnemdjzmqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZydnhxY2lhY3lybmVtZGp6bXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Njg3MTYsImV4cCI6MjA1OTQ0NDcxNn0.koZ3pvJvWbZbcApzxmM29doPJnhu98hB7y_VyVn8KPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);