
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwmhwkdpfihfhoancvts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3bWh3a2RwZmloZmhvYW5jdnRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTA4NzQsImV4cCI6MjA2MDU2Njg3NH0.xZ9qTPLxeCivS-eKW6CahOeiIH5JT3tOBRHsEP3-YKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
